// The catalogue is a design sample, not a directory of people.
//
// It shipped with thirteen invented officials: stock photographs of real,
// identifiable strangers, presented as named staff of real ministries and
// banks, carrying fabricated addresses on those bodies' own domains —
// j.tursunov@mf.uz, d.xolmatov@cbu.uz — and phone numbers in Tashkent's live
// range. Every one of those is gone. What is left is the organisation itself:
// its name, its sector, its published website, and nothing that belongs to a
// person. Real people reach this catalogue by claiming a handle and entering
// their own details, which is the product working rather than a demo pretending.

export interface Profile {
  id: string;
  category: "gov" | "ministry" | "bank" | "venture" | "startup" | "corp";
  categoryLabel: string;
  name: string;
  fullName: string;      // the organisation — this demo carries no people
  position: string;
  positionRu: string;
  organization: string;
  orgShort: string;
  department?: string;
  website?: string;   // only when the organisation actually publishes one
  avatar?: string;    // a real photograph, supplied by us for a named person
  bannerPosition?: string;  // square logos need a higher crop than photographs
  bannerFit?: "cover" | "contain";  // a small mark should not be upscaled to fill
  education?: string;  // as listed on the person's own profile
  coverColor: string;
  coverAccent: string;
  logoText: string;
  socials: { type: string; handle: string }[];
  tags: string[];
  verified: boolean;
}

export const profiles: Profile[] = [
  // ── GOV ──────────────────────────────────────────────────
  {
    id: "tashkent-inn",
    category: "gov",
    categoryLabel: "Innovatsiya Markazi",
    name: "Toshkent Innovatsiya Markazi",
    fullName: "Toshkent Innovatsiya Markazi",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Toshkent Innovatsiya Markazi",
    orgShort: "TIM",
    department: "Raqamli iqtisodiyot bo'limi",
    website: "tim.uz",
    coverColor: "#1a3a6b",
    coverAccent: "#c8973a",
    logoText: "TIM",
    socials: [{ type: "telegram", handle: "@tim_tashkent" }],
    tags: ["Innovatsiya", "Strategiya", "Raqamli iqtisodiyot"],
    verified: true,
  },
  {
    id: "sadullayev",
    category: "gov",
    categoryLabel: "Agentlik Rahbari",
    name: "Alisher Sadullaev",
    fullName: "Alisher Sadullaev",
    position: "Senator · Yoshlar ishlari agentligi rahbari",
    positionRu: "Сенатор · Руководитель Агентства по делам молодёжи",
    organization: "O'zbekiston Respublikasi Yoshlar ishlari agentligi",
    orgShort: "Yoshlar ishlari agentligi",
    department: "Agentlik rahbariyati",
    website: "gov.uz/oz/yoshlar",
    avatar: "/figma-make/alisher-sadullayev.jpeg",
    bannerPosition: "center 32%",
    coverColor: "#0b2f4a",
    coverAccent: "#38bdf8",
    logoText: "AS",
    socials: [],
    tags: ["Yoshlar siyosati", "Senat", "Stanford"],
    verified: true,
  },
  {
    id: "yoshlar-agentligi",
    category: "gov",
    categoryLabel: "Davlat Agentligi",
    name: "Yoshlar ishlari agentligi",
    fullName: "Yoshlar ishlari agentligi",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston Respublikasi Yoshlar ishlari agentligi",
    orgShort: "Yoshlar ishlari agentligi",
    department: "Yoshlar siyosati",
    website: "gov.uz/oz/yoshlar",
    bannerPosition: "center 32%",
    coverColor: "#0b2f4a",
    coverAccent: "#38bdf8",
    logoText: "YIA",
    socials: [],
    tags: ["Yoshlar siyosati", "Ta'lim", "Tadbirkorlik"],
    verified: true,
  },
  {
    id: "hokimiyat",
    category: "gov",
    categoryLabel: "Davlat Organi",
    name: "Toshkent Hokimiyati",
    fullName: "Toshkent Hokimiyati",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Toshkent shahar Hokimiyati",
    orgShort: "Toshkent Hokimiyati",
    department: "Qurilish va kommunal xo'jalik",
    website: "tashkent.uz",
    coverColor: "#1e4d8c",
    coverAccent: "#e8a020",
    logoText: "TH",
    socials: [{ type: "telegram", handle: "@tashkent_hokimiyat" }],
    tags: ["Shahar boshqaruvi", "Qurilish", "Infratuzilma"],
    verified: true,
  },

  // ── MINISTRY ─────────────────────────────────────────────
  {
    id: "moliya",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "Moliya Vazirligi",
    fullName: "Moliya Vazirligi",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston Respublikasi Moliya Vazirligi",
    orgShort: "Moliya Vazirligi",
    department: "Byudjet siyosati departamenti",
    website: "mf.uz",
    coverColor: "#014421",
    coverAccent: "#4cbb77",
    logoText: "MV",
    socials: [
      { type: "telegram", handle: "@minfin_uz" },
      { type: "web", handle: "mf.uz" },
    ],
    tags: ["Byudjet", "Moliya siyosati", "Soliq"],
    verified: true,
  },
  {
    id: "iqtisodiyot",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "ATKRV",
    fullName: "ATKRV",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Axborot Texnologiyalari va Kommunikatsiyalarini Rivojlantirish Vazirligi",
    orgShort: "ATKRV",
    department: "Investitsiyalar bo'limi",
    website: "minict.uz",
    coverColor: "#1a237e",
    coverAccent: "#818cf8",
    logoText: "ATKRV",
    socials: [
      { type: "linkedin", handle: "sabohat-yusupova" },
      { type: "telegram", handle: "@minict_uz" },
    ],
    tags: ["IT", "Kommunikatsiya", "Investitsiya"],
    verified: true,
  },
  {
    id: "raqamli",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "ATKRV",
    fullName: "ATKRV",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Axborot Texnologiyalari va Kommunikatsiyalarini Rivojlantirish Vazirligi",
    orgShort: "ATKRV",
    department: "Raqamli infratuzilma",
    website: "minict.uz",
    coverColor: "#0f1646",
    coverAccent: "#38bdf8",
    logoText: "ATKRV",
    socials: [
      { type: "telegram", handle: "@minict_uz" },
      { type: "linkedin", handle: "bobur-musayev" },
    ],
    tags: ["IT", "Raqamlashtirish", "E-hukumat"],
    verified: true,
  },

  // ── BANK ─────────────────────────────────────────────────
  {
    id: "nbu",
    category: "bank",
    categoryLabel: "Bank",
    name: "Markaziy Bank",
    fullName: "Markaziy Bank",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston Respublikasi Markaziy Banki",
    orgShort: "Markaziy Bank",
    department: "Pul-kredit siyosati",
    website: "cbu.uz",
    coverColor: "#002a0f",
    coverAccent: "#d4a84b",
    logoText: "MB",
    socials: [
      { type: "telegram", handle: "@cbu_uz_official" },
    ],
    tags: ["Markaziy Bank", "Pul siyosati", "Regulyatsiya"],
    verified: true,
  },
  {
    id: "agrobank",
    category: "bank",
    categoryLabel: "Bank",
    name: "Agrobank",
    fullName: "Agrobank",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Agro'sanoat Banki AJ",
    orgShort: "Agrobank",
    department: "Korporativ xizmatlar",
    website: "agrobank.uz",
    coverColor: "#0a3c14",
    coverAccent: "#6ee7b7",
    logoText: "AG",
    socials: [
      { type: "telegram", handle: "@agrobank_uz" },
    ],
    tags: ["Agrosanoat", "Kredit", "Korporativ xizmat"],
    verified: true,
  },
  {
    id: "kapitalbank",
    category: "bank",
    categoryLabel: "Bank",
    name: "Kapital Bank",
    fullName: "Kapital Bank",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Kapital Bank AJ",
    orgShort: "Kapital Bank",
    department: "Raqamli innovatsiyalar",
    website: "kapitalbank.uz",
    coverColor: "#5a0000",
    coverAccent: "#fca5a5",
    logoText: "KB",
    socials: [
      { type: "telegram", handle: "@kapitalbank_uz" },
      { type: "instagram", handle: "@kapitalbank" },
    ],
    tags: ["Fintech", "Raqamli bank", "Kartalar"],
    verified: true,
  },

  // ── VENTURE ──────────────────────────────────────────────
  {
    id: "yakubov",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    name: "Abdulaziz Yakubov",
    fullName: "Abdulaziz Yakubov",
    // Title, employer and dates as published on his own LinkedIn profile.
    position: "Yoshlar Ventures bosh direktori",
    positionRu: "Генеральный директор Yoshlar Ventures",
    organization: "Yoshlar Ventures",
    orgShort: "Yoshlar Ventures",
    department: "UzCombinator kengashi a'zosi",
    website: "yoshlarventures.uz",
    education: "Politecnico di Torino",
    avatar: "/figma-make/abdulaziz-yakubov.jpeg",
    coverColor: "#1e0e00",
    coverAccent: "#fb923c",
    logoText: "YV",
    socials: [{ type: "linkedin", handle: "abdulaziz-yakubov" }],
    tags: ["Venchur kapital", "Investitsiya", "Startap"],
    verified: true,
  },
  {
    id: "ismatov",
    category: "venture",
    // Title, employers and side roles as published on his own LinkedIn profile.
    categoryLabel: "UzCombinator Hammuassisi",
    name: "Ulug'bek Ismatov",
    fullName: "Ulug'bek Ismatov",
    position: "UzCombinator hammuassisi, MPMG bosh direktori",
    positionRu: "Сооснователь UzCombinator, генеральный директор MPMG",
    department: "UzChess bosh direktori · AICA hammuassisi",
    avatar: "/figma-make/ulugbek-ismatov.jpeg",
    organization: "UzCombinator",
    orgShort: "UzCombinator",
    website: "uzcombinator.uz",
    coverColor: "#1c1109",
    coverAccent: "#f97316",
    logoText: "UZC",
    verified: true,
    socials: [{ type: "linkedin", handle: "ulugbek-ismatov" }],
    tags: ["Startap ekotizimi", "Shaxmat", "Sun'iy intellekt"],
  },
  {
    id: "xondamirovna",
    category: "venture",
    categoryLabel: "UzCombinator Hammuassisi",
    name: "Laylo Xondamirovna",
    fullName: "Laylo Xondamirovna",
    position: "UzCombinator hammuassisi, UnicornTech asoschisi",
    positionRu: "Сооснователь UzCombinator, основатель UnicornTech",
    department: "Yoshlar Ventures venchur tahlilchisi",
    education: "Filologiya fanlari doktori, dotsent",
    avatar: "/figma-make/laylo-xondamirovna.jpeg",
    organization: "UzCombinator",
    orgShort: "UzCombinator",
    website: "uzcombinator.uz",
    coverColor: "#1c1109",
    coverAccent: "#f97316",
    logoText: "UZC",
    verified: true,
    socials: [{ type: "linkedin", handle: "xondamirovna" }],
    tags: ["Venchur ta'lim", "Media", "Startap"],
  },
  {
    id: "ismailov",
    category: "venture",
    categoryLabel: "UzCombinator Hammuassisi",
    name: "Murodillo Ismailov",
    fullName: "Murodillo Ismailov",
    position: "UzCombinator hammuassisi, TOKCHA asoschisi va rahbari",
    positionRu: "Сооснователь UzCombinator, основатель и CEO TOKCHA",
    department: "TOKCHA — raqamli kutubxona",
    avatar: "/figma-make/murodillo-ismailov.jpeg",
    organization: "UzCombinator",
    orgShort: "UzCombinator",
    website: "uzcombinator.uz",
    coverColor: "#1c1109",
    coverAccent: "#f97316",
    logoText: "UZC",
    verified: true,
    socials: [{ type: "linkedin", handle: "murodillo-ismailov" }],
    tags: ["Startap", "Dizayn", "Mahsulot"],
  },
  {
    id: "khashimov",
    category: "corp",
    categoryLabel: "Asoschi va Rais",
    name: "Zafar Khashimov",
    fullName: "Zafar Khashimov",
    position: "Korzinka asoschisi va Kengash raisi",
    positionRu: "Основатель и председатель совета Korzinka",
    organization: "Korzinka",
    orgShort: "Korzinka",
    department: "TEAM University ta'sischi aksiyadori",
    website: "korzinka.uz",
    education: "Toshkent davlat universiteti",
    avatar: "/figma-make/zafar-khashimov.jpeg",
    coverColor: "#12240f",
    coverAccent: "#fbbf24",
    logoText: "KZ",
    socials: [{ type: "linkedin", handle: "zafar-khashimov" }],
    tags: ["Riteyl", "Tadbirkorlik", "Ta'lim"],
    verified: true,
  },
  {
    id: "ishmukhamedov",
    category: "corp",
    categoryLabel: "Universitet Asoschisi",
    name: "Umidjon Ishmukhamedov",
    fullName: "Umidjon Ishmukhamedov",
    position: "Millat Umidi University asoschisi",
    positionRu: "Основатель Millat Umidi University",
    organization: "Millat Umidi University",
    orgShort: "Millat Umidi University",
    department: "Oxford Saïd Business School bitiruvchisi",
    website: "millatumidi.uz",
    education: "Georgia State University · Oxford Saïd Business School",
    avatar: "/figma-make/umidjon-ishmukhamedov.jpeg",
    coverColor: "#24122e",
    coverAccent: "#d8b4fe",
    logoText: "MU",
    socials: [{ type: "linkedin", handle: "umidjon-ishmukhamedov" }],
    tags: ["Ta'lim", "Universitet", "Tadbirkorlik"],
    verified: true,
  },
  {
    id: "kurbanova",
    category: "startup",
    categoryLabel: "Asoschi va Rahbar",
    name: "Tamilla Kurbanova",
    fullName: "Tamilla Kurbanova",
    position: "Fintellect asoschisi va bosh direktori",
    positionRu: "Основатель и генеральный директор Fintellect",
    organization: "Fintellect",
    orgShort: "Fintellect",
    department: "The Wharton School bitiruvchisi",
    website: "fintellect.io",
    education: "The Wharton School",
    avatar: "/figma-make/tamilla-kurbanova.jpeg",
    coverColor: "#0a1f2e",
    coverAccent: "#67e8f9",
    logoText: "FT",
    socials: [{ type: "linkedin", handle: "tamilla-kurbanova" }],
    tags: ["Fintech", "Moliya", "Startap"],
    verified: true,
  },
  {
    id: "ibragimova",
    category: "corp",
    categoryLabel: "Moliyaviy Savodxonlik",
    name: "Shohida Ibragimova",
    fullName: "Shohida Ibragimova",
    position: "AYOL by CAU — moliyaviy savodxonlik eksperti",
    positionRu: "AYOL by CAU — эксперт по финансовой грамотности",
    organization: "AYOL by CAU",
    orgShort: "AYOL by CAU",
    department: "Investor · Mentor",
    // cau.uz answers but renders from script and titles itself with a phone
    // number, so it could not be confirmed as the university's own site.
    avatar: "/figma-make/shohida-ibragimova.jpeg",
    coverColor: "#2b1020",
    coverAccent: "#f9a8d4",
    logoText: "AYOL",
    socials: [{ type: "linkedin", handle: "shohida-ibragimova" }],
    tags: ["Moliyaviy savodxonlik", "Investitsiya", "Mentorlik"],
    verified: true,
  },
  {
    id: "ismailova",
    category: "corp",
    categoryLabel: "Jamg'arma Rahbari",
    name: "Gulnoza Ismailova",
    fullName: "Gulnoza Ismailova",
    position: "“El-Yurt Umidi” jamg'armasi ijrochi direktori",
    positionRu: "Исполнительный директор фонда «Эл-юрт умиди»",
    organization: "“El-Yurt Umidi” jamg'armasi",
    orgShort: "El-Yurt Umidi",
    department: "Professor, fan doktori",
    // eyuf.org is a placeholder and eyuf.uz belongs to someone else entirely —
    // it renders "Touch By Aptisme" — so no address until one is confirmed.
    avatar: "/figma-make/gulnoza-ismailova.jpeg",
    coverColor: "#141d33",
    coverAccent: "#93c5fd",
    logoText: "EYU",
    socials: [{ type: "linkedin", handle: "gulnoza-ismailova" }],
    tags: ["Ta'lim", "Xalqaro dasturlar", "Yoshlar"],
    verified: true,
  },
  {
    id: "umarov",
    category: "corp",
    categoryLabel: "Olimpiya Qo'mitasi",
    name: "Otabek Umarov",
    fullName: "Otabek Umarov",
    // Roles as published on his own LinkedIn profile. The portrait was supplied
    // by the client, not taken from that profile.
    position: "O'zbekiston MOQ birinchi vitse-prezidenti",
    positionRu: "Первый вице-президент НОК Узбекистана",
    organization: "O'zbekiston Milliy Olimpiya Qo'mitasi",
    orgShort: "Milliy Olimpiya Qo'mitasi",
    department: "Osiyo Olimpiya Kengashi vitse-prezidenti · FIA Senati a'zosi",
    website: "olympic.uz",
    bannerPosition: "center 38%",
    education: "Toshkent avtomobil yo'llari instituti",
    avatar: "/figma-make/otabek-umarov.jpeg",
    coverColor: "#10182f",
    coverAccent: "#f5c451",
    logoText: "MOQ",
    socials: [{ type: "linkedin", handle: "otabek-umarov" }],
    tags: ["Olimpiya harakati", "Sport", "Xalqaro hamkorlik"],
    verified: true,
  },
  {
    id: "sharipov",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    name: "Munis Sharipov",
    // Titles and employers as published on their own LinkedIn profiles.
    fullName: "Munis Sharipov",
    position: "United Ventures bosh direktori",
    positionRu: "Генеральный директор United Ventures",
    department: "Fintech · HealthTech · Investitsiya",
    education: "Toshkent davlat iqtisodiyot universiteti",
    avatar: "/figma-make/munis-sharipov.jpeg",
    organization: "United Ventures",
    orgShort: "United Ventures",
    website: "uventures.uz",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    verified: true,
    socials: [{ type: "linkedin", handle: "munis-sharipov" }],
    tags: ["Fintech", "Investitsiya", "Venchur kapital"],
  },
  {
    id: "shukurlaev",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    // The link given was /in/sherzod-akhadovich; the profile publishes the name
    // Sherzod Shukurlaev, so that is what the card carries.
    name: "Sherzod Shukurlaev",
    fullName: "Sherzod Shukurlaev",
    position: "United Ventures bosh direktori o'rinbosari",
    positionRu: "Заместитель генерального директора United Ventures",
    department: "Akseleratsiya dasturi rahbari",
    education: "SRH Berlin University of Applied Sciences",
    avatar: "/figma-make/sherzod-shukurlaev.jpeg",
    organization: "United Ventures",
    orgShort: "United Ventures",
    website: "uventures.uz",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    verified: true,
    socials: [{ type: "linkedin", handle: "sherzod-akhadovich" }],
    tags: ["Venchur", "Akseleratsiya", "Biznes rivojlantirish"],
  },
  {
    id: "nodirov",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    name: "Dalerkhon Nodirov",
    fullName: "Dalerkhon Nodirov",
    position: "IT Park Ventures bosh direktori",
    positionRu: "Генеральный директор IT Park Ventures",
    organization: "IT Park Ventures",
    orgShort: "IT Park Ventures",
    department: "Venture Principal",
    website: "itparkventures.uz",
    education: "Westminster International University in Tashkent",
    avatar: "/figma-make/dalerkhon-nodirov.jpeg",
    coverColor: "#0e3006",
    coverAccent: "#a3e635",
    logoText: "ITPV",
    socials: [{ type: "linkedin", handle: "dalerkhon-nodirov" }],
    tags: ["Venchur kapital", "IT", "Investitsiya"],
    verified: true,
  },
  {
    id: "yuldasheva",
    category: "corp",
    categoryLabel: "Key Account Management",
    name: "Zarina Yuldasheva",
    // Title as published on her own LinkedIn profile.
    fullName: "Zarina Yuldasheva",
    position: "IT Park Uzbekistan Key Account Management bosh menejeri",
    positionRu: "Главный менеджер отдела Key Account Management IT Park Uzbekistan",
    department: "Strategik hamkorlik va sheriklik",
    organization: "IT Park Uzbekistan",
    orgShort: "IT Park Uzbekistan",
    website: "it-park.uz",
    avatar: "/figma-make/zarina-yuldasheva.jpeg",
    coverColor: "#0e3006",
    coverAccent: "#bef264",
    logoText: "ITP",
    socials: [{ type: "linkedin", handle: "zarina-yuldasheva" }],
    tags: ["Strategik hamkorlik", "IT eksport", "Ekotizim"],
    verified: true,
  },
  {
    id: "obidjonova",
    category: "corp",
    categoryLabel: "Xalqaro Hamkorlik",
    name: "Zarina Obidjonova",
    // Titles as published on their own LinkedIn profiles.
    fullName: "Zarina Obidjonova",
    position: "IT Park Uzbekistan xalqaro hamkorlik bosh menejeri",
    positionRu: "Главный менеджер по международному сотрудничеству IT Park Uzbekistan",
    department: "ICT Week · OTS Technology Forum",
    education: "Westminster International University in Tashkent",
    avatar: "/figma-make/zarina-obidjonova.jpeg",
    organization: "IT Park Uzbekistan",
    orgShort: "IT Park Uzbekistan",
    website: "it-park.uz",
    coverColor: "#0e3006",
    coverAccent: "#bef264",
    logoText: "ITP",
    verified: true,
    socials: [{ type: "linkedin", handle: "zarina-obidjonova" }],
    tags: ["Xalqaro hamkorlik", "IT ekotizimi", "Tadbirlar"],
  },
  {
    id: "matyakubov",
    category: "corp",
    categoryLabel: "Startap Ekotizimi",
    name: "Vaisbek Matyakubov",
    fullName: "Vaisbek Matyakubov",
    position: "Startap ekotizimi va venchur investitsiyalar menejeri",
    positionRu: "Менеджер по развитию стартап-экосистемы и венчурным инвестициям",
    department: "Women in Tech Uzbekistan direktori yordamchisi",
    avatar: "/figma-make/vaisbek-matyakubov.jpeg",
    organization: "IT Park Uzbekistan",
    orgShort: "IT Park Uzbekistan",
    website: "it-park.uz",
    coverColor: "#0e3006",
    coverAccent: "#bef264",
    logoText: "ITP",
    verified: true,
    socials: [{ type: "linkedin", handle: "vaisbek-matyakubov" }],
    tags: ["Startap ekotizimi", "Venchur investitsiya", "Women in Tech"],
  },
  {
    id: "tojiev",
    category: "startup",
    categoryLabel: "Asoschi va Rahbar",
    name: "Alisher Tojiev",
    // Titles as published on his own LinkedIn profile.
    fullName: "Alisher Tojiev",
    position: "DOMO asoschisi va bosh direktori",
    positionRu: "Основатель и генеральный директор DOMO",
    organization: "DOMO",
    orgShort: "DOMO",
    department: "HomeTech va FinTech platformasi · 2,3 mln foydalanuvchi",
    website: "domo.uz",
    education: "Prezident huzuridagi Davlat boshqaruvi akademiyasi",
    avatar: "/figma-make/alisher-tojiev.jpeg",
    coverColor: "#0c3f8f",
    coverAccent: "#a8cdf8",
    logoText: "DOMO",
    socials: [{ type: "linkedin", handle: "akhmatovich" }],
    tags: ["FinTech", "HomeTech", "Mobil ilova"],
    verified: true,
  },
  {
    id: "tohirova",
    category: "corp",
    categoryLabel: "Ofis Menejeri",
    name: "Zarina Tohirova",
    fullName: "Zarina Tohirova",
    position: "IT Park Uzbekistan ofis menejeri",
    positionRu: "Офис-менеджер IT Park Uzbekistan",
    organization: "IT Park Uzbekistan",
    orgShort: "IT Park Uzbekistan",
    department: "Xalqaro hamkorlik va tadbirlar",
    website: "it-park.uz",
    avatar: "/figma-make/zarina-tohirova.jpeg",
    coverColor: "#0e3006",
    coverAccent: "#bef264",
    logoText: "ITP",
    socials: [{ type: "linkedin", handle: "zarina-tohirova" }],
    tags: ["IT ekotizimi", "Tadbirlar", "Hamkorlik"],
    verified: true,
  },
  {
    id: "abrorov",
    category: "startup",
    categoryLabel: "Asoschi va Rahbar",
    name: "Javohir Abrorov",
    fullName: "Javohir Abrorov",
    // His LinkedIn still lists an earlier venture; these are the roles he holds.
    position: "FLEX asoschisi va bosh direktori",
    positionRu: "Основатель и генеральный директор FLEX",
    department: "MC Legal yuridik firmasi rahbari · biznes yurist",
    organization: "FLEX",
    orgShort: "FLEX",
    website: "flex.com.uz",
    coverColor: "#161a2e",
    coverAccent: "#b4f01e",
    logoText: "FLEX",
    verified: true,
    avatar: "/figma-make/javohir-abrorov.jpeg",
    socials: [{ type: "linkedin", handle: "javohir-abrorov" }],
    tags: ["Biznes huquqi", "NFC", "Tadbirkorlik"],
  },
  {
    id: "ahmadjonov",
    category: "startup",
    categoryLabel: "Hammuassis",
    name: "Abdujabbor Ahmadjonov",
    fullName: "Abdujabbor Ahmadjonov",
    position: "FLEX hammuassisi",
    positionRu: "Сооснователь FLEX",
    department: "Mobil dasturchi · G-Pioneers asoschisi",
    education: "University of Alberta",
    organization: "FLEX",
    orgShort: "FLEX",
    website: "flex.com.uz",
    coverColor: "#161a2e",
    coverAccent: "#b4f01e",
    logoText: "FLEX",
    verified: true,
    avatar: "/figma-make/abdujabbor-ahmadjonov.jpeg",
    socials: [{ type: "linkedin", handle: "abdujabborahmadjonov" }],
    tags: ["Dasturlash", "Mobil ilova", "STEM"],
  },
  {
    id: "abduvohidov",
    category: "startup",
    categoryLabel: "Bosh Texnolog",
    name: "Zoyirjon Abduvohidov",
    fullName: "Zoyirjon Abduvohidov",
    position: "FLEX bosh texnologi",
    positionRu: "Технический директор FLEX",
    department: "DevOps muhandisi",
    education: "INHA University in Tashkent",
    organization: "FLEX",
    orgShort: "FLEX",
    website: "flex.com.uz",
    coverColor: "#161a2e",
    coverAccent: "#b4f01e",
    logoText: "FLEX",
    verified: true,
    avatar: "/figma-make/zoyirjon-abduvohidov.jpeg",
    socials: [{ type: "linkedin", handle: "zoyirjon-abduvohidov" }],
    tags: ["DevOps", "Infratuzilma", "Backend"],
  },
  {
    id: "umurzakov",
    category: "gov",
    categoryLabel: "Agentlik Direktori",
    name: "Sardor Umurzakov",
    // Title and employer as published on his own LinkedIn profile.
    fullName: "Sardor Umurzakov",
    position: "Strategik rivojlanish va islohotlar agentligi direktori",
    positionRu: "Директор Агентства стратегического развития и реформ",
    organization: "Prezident huzuridagi Strategik rivojlanish va islohotlar agentligi",
    orgShort: "Strategik rivojlanish agentligi",
    department: "Prezident Administratsiyasi",
    website: "asdr.uz",
    education: "Toshkent moliya instituti",
    avatar: "/figma-make/sardor-umurzakov.jpeg",
    coverColor: "#2b2b33",
    coverAccent: "#f0c674",
    logoText: "SRIA",
    socials: [{ type: "linkedin", handle: "sardor-umurzakov" }],
    tags: ["Strategik rivojlanish", "Islohotlar", "Iqtisodiyot"],
    verified: true,
  },
  {
    id: "baxtiyarovich",
    category: "corp",
    categoryLabel: "Teleboshlovchi",
    name: "Abror Baxtiyarovich",
    // His LinkedIn carries no headline at all — the presenting role and the
    // portrait came from the client.
    fullName: "Abror Baxtiyarovich",
    position: "Bo telekanali boshlovchisi",
    positionRu: "Ведущий телеканала Bo",
    organization: "Bo telekanali",
    orgShort: "Bo telekanali",
    department: "Taqdimot ko'rsatuvi boshlovchisi · tadbirkor",
    avatar: "/figma-make/abror-baxtiyarovich.jpeg",
    coverColor: "#33203a",
    coverAccent: "#f0b8e0",
    logoText: "BO",
    socials: [{ type: "linkedin", handle: "abror-baxtiyarovich-191955273" }],
    tags: ["Teleko'rsatuv", "Taqdimot", "Tadbirkorlik"],
    verified: true,
  },
  {
    id: "parmonov",
    category: "venture",
    categoryLabel: "Sherik",
    name: "Davron Parmonov",
    // Titles as published on their own LinkedIn profiles.
    fullName: "Davron Parmonov",
    position: "AloqaVentures sherigi va direktor o'rinbosari",
    positionRu: "Партнёр и заместитель директора AloqaVentures",
    department: "Nexus Angel Club asoschisi · IT Park Ventures maslahatchisi",
    avatar: "/figma-make/davron-parmonov.jpeg",
    organization: "AloqaVentures",
    orgShort: "AloqaVentures",
    website: "www.aloqaventures.uz",
    bannerPosition: "center 22%",
    coverColor: "#002066",
    coverAccent: "#7cc8fb",
    logoText: "AV",
    verified: true,
    socials: [{ type: "linkedin", handle: "davronparmonov" }],
    tags: ["Venchur kapital", "Angel investitsiya", "M&A"],
  },
  {
    id: "abdullaev",
    category: "venture",
    categoryLabel: "Principal",
    name: "Mirolim Abdullaev",
    fullName: "Mirolim Abdullaev",
    position: "AloqaVentures principal",
    positionRu: "Принципал AloqaVentures",
    department: "Investitsiya jamoasi",
    education: "Toshkent moliya instituti",
    avatar: "/figma-make/mirolim-abdullaev.jpeg",
    organization: "AloqaVentures",
    orgShort: "AloqaVentures",
    website: "www.aloqaventures.uz",
    bannerPosition: "center 22%",
    coverColor: "#002066",
    coverAccent: "#7cc8fb",
    logoText: "AV",
    verified: true,
    socials: [{ type: "linkedin", handle: "mirolim-abdullaev" }],
    tags: ["Venchur kapital", "Investitsiya", "Startap"],
  },
  {
    id: "gaybulloev",
    category: "venture",
    categoryLabel: "Boshqaruvchi Sherik",
    name: "Sukhrob Gaybulloev",
    fullName: "Sukhrob Gaybulloev",
    position: "AloqaVentures boshqaruvchi sherigi",
    positionRu: "Управляющий партнёр AloqaVentures",
    organization: "AloqaVentures",
    orgShort: "AloqaVentures",
    department: "Aloqabank venchur yo'nalishi",
    website: "www.aloqaventures.uz",
    education: "Toshkent moliya instituti",
    avatar: "/figma-make/sukhrob-gaybulloev.jpeg",
    coverColor: "#002066",
    coverAccent: "#7cc8fb",
    logoText: "AV",
    socials: [{ type: "linkedin", handle: "sukhrob-gaybulloev" }],
    tags: ["Venchur kapital", "Investitsiya", "Bank"],
    verified: true,
  },
  {
    id: "sanakulov",
    category: "venture",
    categoryLabel: "Venchur Tahlilchi",
    name: "Islombek Sanakulov",
    fullName: "Islombek Sanakulov",
    position: "AloqaVentures venchur tahlilchisi",
    positionRu: "Венчурный аналитик AloqaVentures",
    organization: "AloqaVentures",
    orgShort: "AloqaVentures",
    department: "Deal sourcing · Startap tahlili",
    website: "www.aloqaventures.uz",
    education: "Westminster International University in Tashkent",
    avatar: "/figma-make/islombek-sanakulov.jpeg",
    coverColor: "#002066",
    coverAccent: "#7cc8fb",
    logoText: "AV",
    socials: [{ type: "linkedin", handle: "islombek-sanakulov" }],
    tags: ["Venchur kapital", "Startap", "Tahlil"],
    verified: true,
  },
  {
    id: "uzv-fund",
    category: "venture",
    categoryLabel: "Venture Fond",
    name: "Yoshlar Ventures",
    fullName: "Yoshlar Ventures",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Yoshlar Ventures Fund",
    orgShort: "Yoshlar Ventures",
    department: "Portfolio boshqaruvi",
    website: "yoshlarventures.uz",
    coverColor: "#1e0e00",
    coverAccent: "#fb923c",
    logoText: "YV",
    socials: [
      { type: "linkedin", handle: "kamola-nazarova" },
      { type: "telegram", handle: "@yoshlar_vc" },
    ],
    tags: ["Startup", "Investitsiya", "Yosh tadbirkor"],
    verified: true,
  },
  {
    id: "uzfar",
    category: "venture",
    categoryLabel: "Fond",
    name: "United Ventures",
    fullName: "United Ventures",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "United Ventures Uzbekistan",
    orgShort: "United Ventures",
    department: "Boshqaruv hamkorlik",
    website: "uventures.uz",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    socials: [
      { type: "linkedin", handle: "timur-abdullayev" },
      { type: "twitter", handle: "@unitedventures_uz" },
    ],
    tags: ["Islohotlar", "Strategiya", "Taraqqiyot"],
    verified: true,
  },

  // ── CORP ─────────────────────────────────────────────────
  {
    id: "itpark",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "IT Park Uzbekistan",
    fullName: "IT Park Uzbekistan",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston IT Park",
    orgShort: "IT Park",
    department: "Startaplar ekotizimi",
    website: "it-park.uz",
    coverColor: "#0e3006",
    coverAccent: "#a3e635",
    logoText: "ITP",
    socials: [
      { type: "telegram", handle: "@itpark_uz" },
      { type: "instagram", handle: "@itpark_uzbekistan" },
    ],
    tags: ["IT", "Startap", "Innovatsiya"],
    verified: true,
  },
  {
    id: "chamber",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "Startup Garage",
    fullName: "Startup Garage",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Startup Garage Uzbekistan",
    orgShort: "Startup Garage",
    department: "Biznes akseleratsiya",
    website: "startupgarage.uz",
    coverColor: "#1c0c50",
    coverAccent: "#c4b5fd",
    logoText: "SG",
    socials: [
      { type: "telegram", handle: "@startup_garage_uz" },
      { type: "linkedin", handle: "startup-garage-uz" },
    ],
    tags: ["Akseleratsiya", "Mentorlik", "Biznes"],
    verified: true,
  },
  {
    id: "uzreport",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "ICT Week Uzbekistan",
    fullName: "ICT Week Uzbekistan",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "ICT Week Uzbekistan",
    orgShort: "ICT Week",
    department: "Xalqaro hamkorlik",
    website: "ictweek.uz",
    coverColor: "#05123c",
    coverAccent: "#38bdf8",
    logoText: "ICT",
    socials: [
      { type: "telegram", handle: "@ictweek_uz" },
      { type: "instagram", handle: "@ictweek.uz" },
    ],
    tags: ["ICT", "Forum", "Raqamlashtirish"],
    verified: true,
  },
];
