export interface Profile {
  id: string;
  category: "gov" | "ministry" | "bank" | "venture" | "corp";
  categoryLabel: string;
  name: string;
  fullName: string;
  position: string;
  positionRu: string;
  organization: string;
  orgShort: string;
  department?: string;
  phone: string;
  email: string;
  website: string;
  address: string;
  gender: "male" | "female";
  age: number;
  avatar: string;
  coverColor: string;
  coverAccent: string;
  logoText: string;
  socials: { type: string; handle: string }[];
  tags: string[];
  verified: boolean;
}

export const profiles: Profile[] = [
  // ── GOV ──────────────────────────────────────────────────
  {
    id: "tashkent-inn",
    category: "gov",
    categoryLabel: "Innovatsiya Markazi",
    name: "Toshkent Innovatsiya Markazi",
    fullName: "Alisher Karimov Behruzovich",
    position: "Innovatsiya va strategiya bo'limi direktori",
    positionRu: "Директор отдела инноваций и стратегии",
    organization: "Toshkent Innovatsiya Markazi",
    orgShort: "TIM",
    department: "Raqamli iqtisodiyot bo'limi",
    phone: "+998 71 239 54 12",
    email: "a.karimov@tim.uz",
    website: "tim.uz",
    address: "Toshkent, Mirobod tumani, 4-ko'cha, 1-uy",
    gender: "male",
    age: 48,
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&auto=format",
    coverColor: "#1a3a6b",
    coverAccent: "#c8973a",
    logoText: "TIM",
    socials: [{ type: "telegram", handle: "@tim_tashkent" }],
    tags: ["Innovatsiya", "Strategiya", "Raqamli iqtisodiyot"],
    verified: true,
  },
  {
    id: "hokimiyat",
    category: "gov",
    categoryLabel: "Davlat Organi",
    name: "Toshkent Hokimiyati",
    fullName: "Nilufar Rashidova Hamidovna",
    position: "Toshkent shahar Hokimi o'rinbosari",
    positionRu: "Заместитель Хокима г. Ташкент",
    organization: "Toshkent shahar Hokimiyati",
    orgShort: "Toshkent Hokimiyati",
    department: "Qurilish va kommunal xo'jalik",
    phone: "+998 71 233 88 00",
    email: "n.rashidova@tashkent.uz",
    website: "tashkent.uz",
    address: "Toshkent, Shayxontohur tumani, Amir Temur shoh. 6",
    gender: "female",
    age: 44,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&auto=format",
    coverColor: "#1e4d8c",
    coverAccent: "#e8a020",
    logoText: "TH",
    socials: [{ type: "telegram", handle: "@tashkent_hokimiyat" }],
    tags: ["Shahar boshqaruvi", "Qurilish", "Infratuzilma"],
    verified: true,
  },

  // ── MINISTRY ─────────────────────────────────────────────
  {
    id: "moliya",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "Moliya Vazirligi",
    fullName: "Jasur Tursunov Erkinovich",
    position: "Davlat Kotibi — Moliya Vazirligi",
    positionRu: "Государственный Секретарь Министерства Финансов",
    organization: "O'zbekiston Respublikasi Moliya Vazirligi",
    orgShort: "Moliya Vazirligi",
    department: "Byudjet siyosati departamenti",
    phone: "+998 71 239 19 01",
    email: "j.tursunov@mf.uz",
    website: "mf.uz",
    address: "Toshkent, Mirobod tumani, Mustaqillik maydoni, 5",
    gender: "male",
    age: 52,
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&auto=format",
    coverColor: "#014421",
    coverAccent: "#4cbb77",
    logoText: "MV",
    socials: [
      { type: "telegram", handle: "@minfin_uz" },
      { type: "web", handle: "mf.uz" },
    ],
    tags: ["Byudjet", "Moliya siyosati", "Soliq"],
    verified: true,
  },
  {
    id: "iqtisodiyot",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "ATKRV",
    fullName: "Sabohat Yusupova Ilhomovna",
    position: "Axborot texnologiyalari investitsiyalar bo'lim boshlig'i",
    positionRu: "Начальник отдела инвестиций в IT",
    organization: "Axborot Texnologiyalari va Kommunikatsiyalarini Rivojlantirish Vazirligi",
    orgShort: "ATKRV",
    department: "Investitsiyalar bo'limi",
    phone: "+998 71 238 50 00",
    email: "s.yusupova@minict.uz",
    website: "minict.uz",
    address: "Toshkent, Shayxontohur tumani, Mustaqillik maydoni, 5A",
    gender: "female",
    age: 38,
    avatar: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=200&h=200&fit=crop&auto=format",
    coverColor: "#1a237e",
    coverAccent: "#818cf8",
    logoText: "ATKRV",
    socials: [
      { type: "linkedin", handle: "sabohat-yusupova" },
      { type: "telegram", handle: "@minict_uz" },
    ],
    tags: ["IT", "Kommunikatsiya", "Investitsiya"],
    verified: true,
  },
  {
    id: "raqamli",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "ATKRV",
    fullName: "Bobur Musayev Ravshan o'g'li",
    position: "Raqamlashtirish loyihalari direktori — ATKRV",
    positionRu: "Директор проектов цифровизации",
    organization: "Axborot Texnologiyalari va Kommunikatsiyalarini Rivojlantirish Vazirligi",
    orgShort: "ATKRV",
    department: "Raqamli infratuzilma",
    phone: "+998 71 200 02 00",
    email: "b.musayev@minict.uz",
    website: "minict.uz",
    address: "Toshkent, Yakkasaroy tumani, Navoiy ko'chasi, 28",
    gender: "male",
    age: 34,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format",
    coverColor: "#0f1646",
    coverAccent: "#38bdf8",
    logoText: "ATKRV",
    socials: [
      { type: "telegram", handle: "@minict_uz" },
      { type: "linkedin", handle: "bobur-musayev" },
    ],
    tags: ["IT", "Raqamlashtirish", "E-hukumat"],
    verified: true,
  },

  // ── BANK ─────────────────────────────────────────────────
  {
    id: "nbu",
    category: "bank",
    categoryLabel: "Bank",
    name: "Markaziy Bank",
    fullName: "Doniyor Xolmatov Baxtiyor o'g'li",
    position: "Pul-kredit siyosati departamenti direktori",
    positionRu: "Директор Департамента денежно-кредитной политики",
    organization: "O'zbekiston Respublikasi Markaziy Banki",
    orgShort: "Markaziy Bank",
    department: "Pul-kredit siyosati",
    phone: "+998 71 327 60 61",
    email: "d.xolmatov@cbu.uz",
    website: "cbu.uz",
    address: "Toshkent, Mirzo Ulug'bek tumani, Yangi Serqo'rg'on ko'ch., 101",
    gender: "male",
    age: 46,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&auto=format",
    coverColor: "#002a0f",
    coverAccent: "#d4a84b",
    logoText: "MB",
    socials: [
      { type: "telegram", handle: "@cbu_uz_official" },
    ],
    tags: ["Markaziy Bank", "Pul siyosati", "Regulyatsiya"],
    verified: true,
  },
  {
    id: "agrobank",
    category: "bank",
    categoryLabel: "Bank",
    name: "Agrobank",
    fullName: "Maftuna Ergasheva Sodiqovna",
    position: "Korporativ mijozlar bo'limi boshlig'i",
    positionRu: "Руководитель отдела корпоративных клиентов",
    organization: "Agro'sanoat Banki AJ",
    orgShort: "Agrobank",
    department: "Korporativ xizmatlar",
    phone: "+998 71 207 88 88",
    email: "m.ergasheva@agrobank.uz",
    website: "agrobank.uz",
    address: "Toshkent, Chilonzor tumani, Bunyodkor shoh. 112",
    gender: "female",
    age: 35,
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&auto=format",
    coverColor: "#0a3c14",
    coverAccent: "#6ee7b7",
    logoText: "AG",
    socials: [
      { type: "telegram", handle: "@agrobank_uz" },
    ],
    tags: ["Agrosanoat", "Kredit", "Korporativ xizmat"],
    verified: true,
  },
  {
    id: "kapitalbank",
    category: "bank",
    categoryLabel: "Bank",
    name: "Kapital Bank",
    fullName: "Sanjar Botirov Ulmas o'g'li",
    position: "Raqamli mahsulotlar va fintech direktori",
    positionRu: "Директор цифровых продуктов",
    organization: "Kapital Bank AJ",
    orgShort: "Kapital Bank",
    department: "Raqamli innovatsiyalar",
    phone: "+998 78 148 11 11",
    email: "s.botirov@kapitalbank.uz",
    website: "kapitalbank.uz",
    address: "Toshkent, Yakkasaroy tumani, Amir Temur shoh. 105",
    gender: "male",
    age: 31,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&auto=format",
    coverColor: "#5a0000",
    coverAccent: "#fca5a5",
    logoText: "KB",
    socials: [
      { type: "telegram", handle: "@kapitalbank_uz" },
      { type: "instagram", handle: "@kapitalbank" },
    ],
    tags: ["Fintech", "Raqamli bank", "Kartalar"],
    verified: true,
  },

  // ── VENTURE ──────────────────────────────────────────────
  {
    id: "uzv-fund",
    category: "venture",
    categoryLabel: "Venture Fond",
    name: "Yoshlar Ventures",
    fullName: "Kamola Nazarova Baxtiyor qizi",
    position: "Investitsiya direktori — Yoshlar Ventures",
    positionRu: "Директор по инвестициям",
    organization: "Yoshlar Ventures Fund",
    orgShort: "Yoshlar Ventures",
    department: "Portfolio boshqaruvi",
    phone: "+998 71 100 25 25",
    email: "k.nazarova@yoshlar.vc",
    website: "yoshlar.vc",
    address: "Toshkent IT Park, Amir Temur shoh. 108",
    gender: "female",
    age: 33,
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&auto=format",
    coverColor: "#1e0e00",
    coverAccent: "#fb923c",
    logoText: "YV",
    socials: [
      { type: "linkedin", handle: "kamola-nazarova" },
      { type: "telegram", handle: "@yoshlar_vc" },
    ],
    tags: ["Startup", "Investitsiya", "Yosh tadbirkor"],
    verified: true,
  },
  {
    id: "uzfar",
    category: "venture",
    categoryLabel: "Fond",
    name: "United Ventures",
    fullName: "Timur Abdullayev Hamid o'g'li",
    position: "Bosh hamkor va asoschisi — United Ventures",
    positionRu: "Управляющий партнёр и основатель",
    organization: "United Ventures Uzbekistan",
    orgShort: "United Ventures",
    department: "Boshqaruv hamkorlik",
    phone: "+998 90 900 01 01",
    email: "t.abdullayev@unitedventures.uz",
    website: "unitedventures.uz",
    address: "Toshkent, Mirzo Ulug'bek tumani, Universitet ko'ch. 15",
    gender: "male",
    age: 40,
    avatar: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=200&h=200&fit=crop&auto=format",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    socials: [
      { type: "linkedin", handle: "timur-abdullayev" },
      { type: "twitter", handle: "@unitedventures_uz" },
    ],
    tags: ["Islohotlar", "Strategiya", "Taraqqiyot"],
    verified: true,
  },

  // ── CORP ─────────────────────────────────────────────────
  {
    id: "itpark",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "IT Park Uzbekistan",
    fullName: "Zulfiya Toshmatova Mansur qizi",
    position: "Startaplar rivojlantirish menejeri — IT Park",
    positionRu: "Менеджер по развитию стартапов",
    organization: "O'zbekiston IT Park",
    orgShort: "IT Park",
    department: "Startaplar ekotizimi",
    phone: "+998 71 200 08 00",
    email: "z.toshmatova@it-park.uz",
    website: "it-park.uz",
    address: "Toshkent shahri, Amir Temur shoh. 107B",
    gender: "female",
    age: 27,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&auto=format",
    coverColor: "#0e3006",
    coverAccent: "#a3e635",
    logoText: "ITP",
    socials: [
      { type: "telegram", handle: "@itpark_uz" },
      { type: "instagram", handle: "@itpark_uzbekistan" },
    ],
    tags: ["IT", "Startap", "Innovatsiya"],
    verified: true,
  },
  {
    id: "chamber",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "Startup Garage",
    fullName: "Ravshan Mirzayev Odil o'g'li",
    position: "Akseleratsiya dasturlari rahbari — Startup Garage",
    positionRu: "Руководитель программ акселерации",
    organization: "Startup Garage Uzbekistan",
    orgShort: "Startup Garage",
    department: "Biznes akseleratsiya",
    phone: "+998 71 232 34 00",
    email: "r.mirzayev@startupgarage.uz",
    website: "startupgarage.uz",
    address: "Toshkent, Mirzo Ulug'bek tumani, Bunyodkor shoh. 6",
    gender: "male",
    age: 43,
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop&auto=format",
    coverColor: "#1c0c50",
    coverAccent: "#c4b5fd",
    logoText: "SG",
    socials: [
      { type: "telegram", handle: "@startup_garage_uz" },
      { type: "linkedin", handle: "startup-garage-uz" },
    ],
    tags: ["Akseleratsiya", "Mentorlik", "Biznes"],
    verified: true,
  },
  {
    id: "uzreport",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "ICT Week Uzbekistan",
    fullName: "Mohinur Xasanova Dilshod qizi",
    position: "Dastur va hamkorlik koordinatori — ICT Week",
    positionRu: "Координатор программ и партнёрств",
    organization: "ICT Week Uzbekistan",
    orgShort: "ICT Week",
    department: "Xalqaro hamkorlik",
    phone: "+998 71 256 78 90",
    email: "m.xasanova@ictweek.uz",
    website: "ictweek.uz",
    address: "Toshkent, Yunusobod tumani, Qatortol ko'ch. 50",
    gender: "female",
    age: 29,
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&auto=format",
    coverColor: "#05123c",
    coverAccent: "#38bdf8",
    logoText: "ICT",
    socials: [
      { type: "telegram", handle: "@ictweek_uz" },
      { type: "instagram", handle: "@ictweek.uz" },
    ],
    tags: ["ICT", "Forum", "Raqamlashtirish"],
    verified: true,
  },
];
