// The catalogue is a design sample, not a directory of people.
//
// It shipped with thirteen invented officials: stock photographs of real,
// identifiable strangers, presented as named staff of real ministries and
// banks, carrying fabricated addresses on those bodies' own domains —
// j.tursunov@mf.uz, d.xolmatov@cbu.uz — and phone numbers in Tashkent's live
// range. Every one of those is gone. What is left is the organisation itself:
// its name, its sector, its published website, and nothing that belongs to a
// person. Real people reach this catalogue by claiming a handle and entering
// their own details, which is the product working rather than a demo pretending.

export interface Profile {
  id: string;
  category: "gov" | "ministry" | "bank" | "venture" | "corp";
  categoryLabel: string;
  name: string;
  fullName: string;      // the organisation — this demo carries no people
  position: string;
  positionRu: string;
  organization: string;
  orgShort: string;
  department?: string;
  website?: string;   // only when the organisation actually publishes one
  avatar?: string;    // a real photograph, supplied by us for a named person
  bannerPosition?: string;  // square logos need a higher crop than photographs
  bannerFit?: "cover" | "contain";  // a small mark should not be upscaled to fill
  coverColor: string;
  coverAccent: string;
  logoText: string;
  socials: { type: string; handle: string }[];
  tags: string[];
  verified: boolean;
}

export const profiles: Profile[] = [
  // ── GOV ──────────────────────────────────────────────────
  {
    id: "tashkent-inn",
    category: "gov",
    categoryLabel: "Innovatsiya Markazi",
    name: "Toshkent Innovatsiya Markazi",
    fullName: "Toshkent Innovatsiya Markazi",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Toshkent Innovatsiya Markazi",
    orgShort: "TIM",
    department: "Raqamli iqtisodiyot bo'limi",
    website: "tim.uz",
    coverColor: "#1a3a6b",
    coverAccent: "#c8973a",
    logoText: "TIM",
    socials: [{ type: "telegram", handle: "@tim_tashkent" }],
    tags: ["Innovatsiya", "Strategiya", "Raqamli iqtisodiyot"],
    verified: true,
  },
  {
    id: "sadullayev",
    category: "gov",
    categoryLabel: "Agentlik Rahbari",
    name: "Alisher Sadullaev",
    fullName: "Alisher Sadullaev",
    position: "Senator · Yoshlar ishlari agentligi rahbari",
    positionRu: "Сенатор · Руководитель Агентства по делам молодёжи",
    organization: "O'zbekiston Respublikasi Yoshlar ishlari agentligi",
    orgShort: "Yoshlar ishlari agentligi",
    department: "Agentlik rahbariyati",
    website: "gov.uz/oz/yoshlar",
    avatar: "/figma-make/alisher-sadullayev.jpeg",
    bannerPosition: "center 32%",
    coverColor: "#0b2f4a",
    coverAccent: "#38bdf8",
    logoText: "AS",
    socials: [],
    tags: ["Yoshlar siyosati", "Senat", "Stanford"],
    verified: true,
  },
  {
    id: "yoshlar-agentligi",
    category: "gov",
    categoryLabel: "Davlat Agentligi",
    name: "Yoshlar ishlari agentligi",
    fullName: "Yoshlar ishlari agentligi",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston Respublikasi Yoshlar ishlari agentligi",
    orgShort: "Yoshlar ishlari agentligi",
    department: "Yoshlar siyosati",
    website: "gov.uz/oz/yoshlar",
    bannerPosition: "center 32%",
    coverColor: "#0b2f4a",
    coverAccent: "#38bdf8",
    logoText: "YIA",
    socials: [],
    tags: ["Yoshlar siyosati", "Ta'lim", "Tadbirkorlik"],
    verified: true,
  },
  {
    id: "hokimiyat",
    category: "gov",
    categoryLabel: "Davlat Organi",
    name: "Toshkent Hokimiyati",
    fullName: "Toshkent Hokimiyati",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Toshkent shahar Hokimiyati",
    orgShort: "Toshkent Hokimiyati",
    department: "Qurilish va kommunal xo'jalik",
    website: "tashkent.uz",
    coverColor: "#1e4d8c",
    coverAccent: "#e8a020",
    logoText: "TH",
    socials: [{ type: "telegram", handle: "@tashkent_hokimiyat" }],
    tags: ["Shahar boshqaruvi", "Qurilish", "Infratuzilma"],
    verified: true,
  },

  // ── MINISTRY ─────────────────────────────────────────────
  {
    id: "moliya",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "Moliya Vazirligi",
    fullName: "Moliya Vazirligi",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston Respublikasi Moliya Vazirligi",
    orgShort: "Moliya Vazirligi",
    department: "Byudjet siyosati departamenti",
    website: "mf.uz",
    coverColor: "#014421",
    coverAccent: "#4cbb77",
    logoText: "MV",
    socials: [
      { type: "telegram", handle: "@minfin_uz" },
      { type: "web", handle: "mf.uz" },
    ],
    tags: ["Byudjet", "Moliya siyosati", "Soliq"],
    verified: true,
  },
  {
    id: "iqtisodiyot",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "ATKRV",
    fullName: "ATKRV",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Axborot Texnologiyalari va Kommunikatsiyalarini Rivojlantirish Vazirligi",
    orgShort: "ATKRV",
    department: "Investitsiyalar bo'limi",
    website: "minict.uz",
    coverColor: "#1a237e",
    coverAccent: "#818cf8",
    logoText: "ATKRV",
    socials: [
      { type: "linkedin", handle: "sabohat-yusupova" },
      { type: "telegram", handle: "@minict_uz" },
    ],
    tags: ["IT", "Kommunikatsiya", "Investitsiya"],
    verified: true,
  },
  {
    id: "raqamli",
    category: "ministry",
    categoryLabel: "Vazirlik",
    name: "ATKRV",
    fullName: "ATKRV",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Axborot Texnologiyalari va Kommunikatsiyalarini Rivojlantirish Vazirligi",
    orgShort: "ATKRV",
    department: "Raqamli infratuzilma",
    website: "minict.uz",
    coverColor: "#0f1646",
    coverAccent: "#38bdf8",
    logoText: "ATKRV",
    socials: [
      { type: "telegram", handle: "@minict_uz" },
      { type: "linkedin", handle: "bobur-musayev" },
    ],
    tags: ["IT", "Raqamlashtirish", "E-hukumat"],
    verified: true,
  },

  // ── BANK ─────────────────────────────────────────────────
  {
    id: "nbu",
    category: "bank",
    categoryLabel: "Bank",
    name: "Markaziy Bank",
    fullName: "Markaziy Bank",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston Respublikasi Markaziy Banki",
    orgShort: "Markaziy Bank",
    department: "Pul-kredit siyosati",
    website: "cbu.uz",
    coverColor: "#002a0f",
    coverAccent: "#d4a84b",
    logoText: "MB",
    socials: [
      { type: "telegram", handle: "@cbu_uz_official" },
    ],
    tags: ["Markaziy Bank", "Pul siyosati", "Regulyatsiya"],
    verified: true,
  },
  {
    id: "agrobank",
    category: "bank",
    categoryLabel: "Bank",
    name: "Agrobank",
    fullName: "Agrobank",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Agro'sanoat Banki AJ",
    orgShort: "Agrobank",
    department: "Korporativ xizmatlar",
    website: "agrobank.uz",
    coverColor: "#0a3c14",
    coverAccent: "#6ee7b7",
    logoText: "AG",
    socials: [
      { type: "telegram", handle: "@agrobank_uz" },
    ],
    tags: ["Agrosanoat", "Kredit", "Korporativ xizmat"],
    verified: true,
  },
  {
    id: "kapitalbank",
    category: "bank",
    categoryLabel: "Bank",
    name: "Kapital Bank",
    fullName: "Kapital Bank",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Kapital Bank AJ",
    orgShort: "Kapital Bank",
    department: "Raqamli innovatsiyalar",
    website: "kapitalbank.uz",
    coverColor: "#5a0000",
    coverAccent: "#fca5a5",
    logoText: "KB",
    socials: [
      { type: "telegram", handle: "@kapitalbank_uz" },
      { type: "instagram", handle: "@kapitalbank" },
    ],
    tags: ["Fintech", "Raqamli bank", "Kartalar"],
    verified: true,
  },

  // ── VENTURE ──────────────────────────────────────────────
  {
    id: "yakubov",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    name: "Abdulaziz Yakubov",
    fullName: "Abdulaziz Yakubov",
    // Title, employer and dates as published on his own LinkedIn profile.
    position: "Yoshlar Ventures bosh direktori",
    positionRu: "Генеральный директор Yoshlar Ventures",
    organization: "Yoshlar Ventures",
    orgShort: "Yoshlar Ventures",
    department: "UzCombinator kengashi a'zosi",
    website: "yoshlarventures.uz",
    avatar: "/figma-make/abdulaziz-yakubov.jpeg",
    coverColor: "#1e0e00",
    coverAccent: "#fb923c",
    logoText: "YV",
    socials: [{ type: "linkedin", handle: "abdulaziz-yakubov" }],
    tags: ["Venchur kapital", "Investitsiya", "Startap"],
    verified: true,
  },
  {
    id: "ismatov",
    category: "venture",
    // Title, employers and side roles as published on his own LinkedIn profile.
    categoryLabel: "UzCombinator Hammuassisi",
    name: "Ulug'bek Ismatov",
    fullName: "Ulug'bek Ismatov",
    position: "UzCombinator hammuassisi, MPMG bosh direktori",
    positionRu: "Сооснователь UzCombinator, генеральный директор MPMG",
    department: "UzChess bosh direktori · AICA hammuassisi",
    avatar: "/figma-make/ulugbek-ismatov.jpeg",
    organization: "UzCombinator",
    orgShort: "UzCombinator",
    website: "uzcombinator.uz",
    coverColor: "#1c1109",
    coverAccent: "#f97316",
    logoText: "UZC",
    verified: true,
    socials: [{ type: "linkedin", handle: "ulugbek-ismatov" }],
    tags: ["Startap ekotizimi", "Shaxmat", "Sun'iy intellekt"],
  },
  {
    id: "xondamirovna",
    category: "venture",
    categoryLabel: "UzCombinator Hammuassisi",
    name: "Laylo Xondamirovna",
    fullName: "Laylo Xondamirovna",
    position: "UzCombinator hammuassisi, UnicornTech asoschisi",
    positionRu: "Сооснователь UzCombinator, основатель UnicornTech",
    department: "Yoshlar Ventures venchur tahlilchisi",
    avatar: "/figma-make/laylo-xondamirovna.jpeg",
    organization: "UzCombinator",
    orgShort: "UzCombinator",
    website: "uzcombinator.uz",
    coverColor: "#1c1109",
    coverAccent: "#f97316",
    logoText: "UZC",
    verified: true,
    socials: [{ type: "linkedin", handle: "xondamirovna" }],
    tags: ["Venchur ta'lim", "Media", "Startap"],
  },
  {
    id: "ismailov",
    category: "venture",
    categoryLabel: "UzCombinator Hammuassisi",
    name: "Murodillo Ismailov",
    fullName: "Murodillo Ismailov",
    position: "UzCombinator hammuassisi, TOKCHA asoschisi va rahbari",
    positionRu: "Сооснователь UzCombinator, основатель и CEO TOKCHA",
    department: "TOKCHA — raqamli kutubxona",
    avatar: "/figma-make/murodillo-ismailov.jpeg",
    organization: "UzCombinator",
    orgShort: "UzCombinator",
    website: "uzcombinator.uz",
    coverColor: "#1c1109",
    coverAccent: "#f97316",
    logoText: "UZC",
    verified: true,
    socials: [{ type: "linkedin", handle: "murodillo-ismailov" }],
    tags: ["Startap", "Dizayn", "Mahsulot"],
  },
  {
    id: "sharipov",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    name: "Munis Sharipov",
    // Titles and employers as published on their own LinkedIn profiles.
    fullName: "Munis Sharipov",
    position: "United Ventures bosh direktori",
    positionRu: "Генеральный директор United Ventures",
    department: "Fintech · HealthTech · Investitsiya",
    avatar: "/figma-make/munis-sharipov.jpeg",
    organization: "United Ventures",
    orgShort: "United Ventures",
    website: "uventures.uz",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    verified: true,
    socials: [{ type: "linkedin", handle: "munis-sharipov" }],
    tags: ["Fintech", "Investitsiya", "Venchur kapital"],
  },
  {
    id: "shukurlaev",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    // The link given was /in/sherzod-akhadovich; the profile publishes the name
    // Sherzod Shukurlaev, so that is what the card carries.
    name: "Sherzod Shukurlaev",
    fullName: "Sherzod Shukurlaev",
    position: "United Ventures bosh direktori o'rinbosari",
    positionRu: "Заместитель генерального директора United Ventures",
    department: "Akseleratsiya dasturi rahbari",
    avatar: "/figma-make/sherzod-shukurlaev.jpeg",
    organization: "United Ventures",
    orgShort: "United Ventures",
    website: "uventures.uz",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    verified: true,
    socials: [{ type: "linkedin", handle: "sherzod-akhadovich" }],
    tags: ["Venchur", "Akseleratsiya", "Biznes rivojlantirish"],
  },
  {
    id: "nodirov",
    category: "venture",
    categoryLabel: "Fond Rahbari",
    name: "Dalerkhon Nodirov",
    fullName: "Dalerkhon Nodirov",
    position: "IT Park Ventures bosh direktori",
    positionRu: "Генеральный директор IT Park Ventures",
    organization: "IT Park Ventures",
    orgShort: "IT Park Ventures",
    department: "Venture Principal",
    website: "itparkventures.uz",
    avatar: "/figma-make/dalerkhon-nodirov.jpeg",
    coverColor: "#0e3006",
    coverAccent: "#a3e635",
    logoText: "ITPV",
    socials: [{ type: "linkedin", handle: "dalerkhon-nodirov" }],
    tags: ["Venchur kapital", "IT", "Investitsiya"],
    verified: true,
  },
  {
    id: "gaybulloev",
    category: "venture",
    categoryLabel: "Boshqaruvchi Sherik",
    name: "Sukhrob Gaybulloev",
    fullName: "Sukhrob Gaybulloev",
    position: "AloqaVentures boshqaruvchi sherigi",
    positionRu: "Управляющий партнёр AloqaVentures",
    organization: "AloqaVentures",
    orgShort: "AloqaVentures",
    department: "Aloqabank venchur yo'nalishi",
    // aloqaventures.uz and .com do not resolve; the fund's own address is not
    // confirmed, and the bank's domain is not the fund's.
    avatar: "/figma-make/sukhrob-gaybulloev.jpeg",
    coverColor: "#062a2e",
    coverAccent: "#2dd4bf",
    logoText: "AV",
    socials: [{ type: "linkedin", handle: "sukhrob-gaybulloev" }],
    tags: ["Venchur kapital", "Investitsiya", "Bank"],
    verified: true,
  },
  {
    id: "sanakulov",
    category: "venture",
    categoryLabel: "Venchur Tahlilchi",
    name: "Islombek Sanakulov",
    fullName: "Islombek Sanakulov",
    position: "AloqaVentures venchur tahlilchisi",
    positionRu: "Венчурный аналитик AloqaVentures",
    organization: "AloqaVentures",
    orgShort: "AloqaVentures",
    department: "Deal sourcing · Startap tahlili",
    avatar: "/figma-make/islombek-sanakulov.jpeg",
    coverColor: "#062a2e",
    coverAccent: "#2dd4bf",
    logoText: "AV",
    socials: [{ type: "linkedin", handle: "islombek-sanakulov" }],
    tags: ["Venchur kapital", "Startap", "Tahlil"],
    verified: true,
  },
  {
    id: "uzv-fund",
    category: "venture",
    categoryLabel: "Venture Fond",
    name: "Yoshlar Ventures",
    fullName: "Yoshlar Ventures",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Yoshlar Ventures Fund",
    orgShort: "Yoshlar Ventures",
    department: "Portfolio boshqaruvi",
    website: "yoshlarventures.uz",
    coverColor: "#1e0e00",
    coverAccent: "#fb923c",
    logoText: "YV",
    socials: [
      { type: "linkedin", handle: "kamola-nazarova" },
      { type: "telegram", handle: "@yoshlar_vc" },
    ],
    tags: ["Startup", "Investitsiya", "Yosh tadbirkor"],
    verified: true,
  },
  {
    id: "uzfar",
    category: "venture",
    categoryLabel: "Fond",
    name: "United Ventures",
    fullName: "United Ventures",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "United Ventures Uzbekistan",
    orgShort: "United Ventures",
    department: "Boshqaruv hamkorlik",
    website: "uventures.uz",
    coverColor: "#052614",
    coverAccent: "#6ee7b7",
    logoText: "UV",
    socials: [
      { type: "linkedin", handle: "timur-abdullayev" },
      { type: "twitter", handle: "@unitedventures_uz" },
    ],
    tags: ["Islohotlar", "Strategiya", "Taraqqiyot"],
    verified: true,
  },

  // ── CORP ─────────────────────────────────────────────────
  {
    id: "itpark",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "IT Park Uzbekistan",
    fullName: "IT Park Uzbekistan",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "O'zbekiston IT Park",
    orgShort: "IT Park",
    department: "Startaplar ekotizimi",
    website: "it-park.uz",
    coverColor: "#0e3006",
    coverAccent: "#a3e635",
    logoText: "ITP",
    socials: [
      { type: "telegram", handle: "@itpark_uz" },
      { type: "instagram", handle: "@itpark_uzbekistan" },
    ],
    tags: ["IT", "Startap", "Innovatsiya"],
    verified: true,
  },
  {
    id: "chamber",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "Startup Garage",
    fullName: "Startup Garage",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "Startup Garage Uzbekistan",
    orgShort: "Startup Garage",
    department: "Biznes akseleratsiya",
    website: "startupgarage.uz",
    coverColor: "#1c0c50",
    coverAccent: "#c4b5fd",
    logoText: "SG",
    socials: [
      { type: "telegram", handle: "@startup_garage_uz" },
      { type: "linkedin", handle: "startup-garage-uz" },
    ],
    tags: ["Akseleratsiya", "Mentorlik", "Biznes"],
    verified: true,
  },
  {
    id: "uzreport",
    category: "corp",
    categoryLabel: "Tashkilot",
    name: "ICT Week Uzbekistan",
    fullName: "ICT Week Uzbekistan",
    position: "Rasmiy tashkilot sahifasi",
    positionRu: "Официальная страница организации",
    organization: "ICT Week Uzbekistan",
    orgShort: "ICT Week",
    department: "Xalqaro hamkorlik",
    website: "ictweek.uz",
    coverColor: "#05123c",
    coverAccent: "#38bdf8",
    logoText: "ICT",
    socials: [
      { type: "telegram", handle: "@ictweek_uz" },
      { type: "instagram", handle: "@ictweek.uz" },
    ],
    tags: ["ICT", "Forum", "Raqamlashtirish"],
    verified: true,
  },
];
